'use client'
import {useState,type FormEvent} from 'react'
import Link from 'next/link'
import '@/components/extras-real/extras-real.css'
type Equipment={id:string;codigo:string;nome:string|null;tipo:string;area:string|null;ativo:boolean}
export function EquipmentClient({localId,localName,initial,types}:{localId:string;localName:string;initial:Equipment[];types:string[]}){
 const [items,setItems]=useState(initial),[edit,setEdit]=useState<Equipment|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function save(data:Record<string,unknown>,method:'POST'|'PATCH'){setBusy(true);setError('');try{const url=`/api/crivo/locais/${localId}/equipamentos`,r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),d=await r.json();if(!r.ok)throw Error(d.error);const reload=await fetch(url,{cache:'no-store'}),list=await reload.json();if(!reload.ok)throw Error(list.error);setItems(list.items);setEdit(null);return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=Object.fromEntries(new FormData(form));if(await save({...data,...(edit?{id:edit.id}:{})},edit?'PATCH':'POST'))form.reset()}
 return <section className="er"><Link className="er-back-link" href={`/crivo/${localId}`}>← Voltar ao local</Link><h1>Equipamentos · {localName}</h1><p>O tipo deve coincidir com o configurado no item do template. Novas auditorias usam os equipamentos ativos; visitas já abertas preservam sua configuração.</p>{error&&<p role="alert" className="er-error">{error}</p>}
 <form className="er-panel er-form" key={edit?.id??'new'} onSubmit={submit}><h2 className="er-wide">{edit?'Editar equipamento':'Adicionar equipamento'}</h2><label>Código<input name="codigo" required maxLength={200} defaultValue={edit?.codigo}/></label><label>Nome<input name="nome" maxLength={200} defaultValue={edit?.nome??''}/></label><label>Tipo<input name="tipo" list="equipment-types" required maxLength={200} defaultValue={edit?.tipo}/><datalist id="equipment-types">{types.map(t=><option key={t} value={t}/>)}</datalist></label><label>Área<input name="area" maxLength={200} defaultValue={edit?.area??''}/></label><div className="er-wide er-buttons"><button disabled={busy}>{busy?'Salvando…':'Salvar equipamento'}</button>{edit&&<button type="button" onClick={()=>setEdit(null)}>Cancelar edição</button>}</div></form>
 <ul className="er-access-list">{items.map(item=><li className="er-panel" key={item.id}><span><strong>{item.codigo} {item.nome}</strong><small>{item.tipo}{item.area?` · ${item.area}`:''} · {item.ativo?'Ativo':'Inativo'}</small></span><div className="er-buttons"><button disabled={busy} onClick={()=>{setEdit(item);window.scrollTo({top:0,behavior:'instant'})}}>Editar</button><button disabled={busy} onClick={()=>save({id:item.id,ativo:!item.ativo},'PATCH')}>{item.ativo?'Desativar':'Reativar'}</button></div></li>)}</ul>{!items.length&&<p>Nenhum equipamento cadastrado neste local.</p>}</section>
}
