import Link from 'next/link';
import type {CrivoReport} from '@/lib/crivo/report';
import {classify} from '@/lib/crivo/scoring';
import {BotaoExportar} from '@/app/(dashboard)/relatorio-diario/painel-geral/_components/botao-exportar';
import '@/components/extras-real/print.css';
import './print-report.css';
const number=(v:number|null|undefined)=>v==null?'—':Number(v).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const date=(s:string|null|undefined)=>s?new Date(s).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Não registrado';
export function CrivoPrintReport({report:r}:{report:CrivoReport}) {
 const e=r.execution,id=e.id;
 const answerMap=new Map(r.responses.map(a=>[a.item_id,a]));
 const quantitative=r.model!=='headchef_narrativo';
 const evaluated=r.items.filter(i=>i.tipo_resposta==='sim_nao'&&answerMap.has(i.id)&&!answerMap.get(i.id)?.nao_aplicavel);
 const yes=evaluated.filter(i=>answerMap.get(i.id)?.resposta?.valor==='sim').length;
 const no=evaluated.filter(i=>answerMap.get(i.id)?.resposta?.valor==='nao').length;
 const total=yes+no, share=total?yes/total*100:0;
 const critical=r.model==='ff_ponderado'?r.items.filter(i=>i.critico&&!answerMap.get(i.id)?.nao_aplicavel&&answerMap.get(i.id)?.resposta?.valor==='nao'):[];
 const orders=[...new Set(r.items.map(i=>i.topico_ordem??0))].sort((a,b)=>a-b);
 const imageUrl=(path:string|null)=>{
  if(!path)return undefined;
  if(/^https?:/.test(path)){try{const url=new URL(path);return url.origin===new URL(process.env.NEXT_PUBLIC_SUPABASE_URL!).origin&&url.pathname.startsWith('/storage/v1/object/public/checklist-photos/')?path:undefined}catch{return undefined}}
  return `/api/crivo/execucoes/${id}/assets?redirect=1&path=${encodeURIComponent(path)}`;
 };
 const mapLink=(lat:number|null,lng:number|null)=>lat!=null&&lng!=null?`https://maps.google.com/?q=${lat},${lng}`:null;
 const start=mapLink(e.geo_inicio_lat,e.geo_inicio_lng), end=mapLink(e.geo_fim_lat,e.geo_fim_lng);
 return <main className="opx-print cr-print"><nav className="print:hidden cr-print-toolbar"><Link href={`/crivo/relatorios/${id}`}>← Revisar laudo e plano</Link><BotaoExportar/></nav>
 <header className="cr-print-cover"><p className="cr-print-brand">MISE / CRIVO · AUDITORIA OPERACIONAL</p><h1>{r.local||r.unit}</h1><h2>{r.title}</h2><p>{r.address||'Endereço não informado'} · {r.unit}</p><div className="cr-print-meta"><p><b>Início</b><br/>{date(e.iniciado_em)}</p><p><b>Conclusão</b><br/>{date(e.concluido_em)}</p><p><b>Avaliador</b><br/>{e.avaliador_nome||'Não informado'}<br/>{e.avaliador_cargo}{e.avaliador_registro?` · ${e.avaliador_registro}`:''}</p></div>
 {e.status!=='concluido'&&<p className="cr-print-draft">EM ELABORAÇÃO · Auditoria ainda não concluída</p>}
 {!e.plano_revisado_em&&<p className="cr-print-draft">PLANO EM REVISÃO · Responsáveis e prazos devem ser conferidos pelo auditor.</p>}
 <div className="cr-print-result"><div><p>{e.status==='concluido'?'Resultado desta visita':'Nota provisória · respostas atuais'}</p><strong>{quantitative?`${number(e.percentual)}${e.percentual==null?'':'%'}`:'Descritivo'}</strong><p>{classify(e.percentual,r.model)}</p></div>{quantitative&&<div><p>Visita anterior</p><strong>{r.previous?.percentual!=null?`${number(r.previous.percentual)}%`:'—'}</strong><p>{r.previous?date(r.previous.concluido_em):'Sem visita anterior comparável'}</p></div>}</div>
 {quantitative&&<div className="cr-print-charts"><figure className="print-avoid"><h2>Conformidade dos itens</h2>{total>0?<><svg viewBox="0 0 42 42" width="150" height="150" role="img" aria-label={`${yes} conformes e ${no} não conformes`}><circle cx="21" cy="21" r="15.9155" fill="none" stroke="#ff6e41" strokeWidth="10"/><circle cx="21" cy="21" r="15.9155" fill="none" stroke="#39342f" strokeWidth="10" strokeDasharray={`${share} ${100-share}`} strokeDashoffset="25"/></svg><figcaption>{yes} conformes · {no} não conformes<br/>Contagem de itens; a nota considera a metodologia do formulário.</figcaption></>:<p>Sem itens avaliados.</p>}</figure><section><h2>Pontos perdidos por tópico</h2>{r.topics.filter(t=>t.percentual!=null&&t.peso>0).map(t=>{const lost=Math.max(0,Number(t.possivel??t.peso)-Number(t.obtido??t.peso*Number(t.percentual)/100));return <div className="cr-print-bar" key={t.topico_ordem}><span>{t.topico_nome}</span><b>{number(lost)}</b><svg viewBox="0 0 100 4" preserveAspectRatio="none" role="img" aria-label={`${number(lost)} pontos perdidos`}><rect width="100" height="4" fill="#e8e2d8"/><rect width={Math.min(100,t.peso?lost/t.peso*100:0)} height="4" fill="#ff6e41"/></svg></div>})}</section></div>}
 {quantitative&&<table><thead><tr><th>Tópico</th><th>Possível</th><th>Obtido</th><th>%</th></tr></thead><tbody>{r.topics.map(t=><tr key={t.topico_ordem}><td>{t.topico_nome}{t.zerado_por_critico&&r.model==='ff_ponderado'? ' *':''}</td><td>{number(t.possivel??t.peso)}</td><td>{number(t.obtido??(t.percentual==null?null:t.peso*t.percentual/100))}</td><td>{t.percentual==null?'N/A':`${number(t.percentual)}%`}</td></tr>)}</tbody></table>}
 {critical.length>0&&<section className="cr-print-critical"><h2>Principais apontamentos críticos</h2><ul>{critical.map(i=><li key={i.id}>{i.topico_nome} · {i.titulo}</li>)}</ul><p>* Não conformidade crítica que zera a nota do tópico.</p></section>}
 <p className="cr-print-geo">Geolocalização: {start?<a href={start}>início ↗</a>:'início não capturado'} · {end?<a href={end}>fim ↗</a>:'fim não capturado'}</p>
 </header>
 {orders.map(order=><section className="print-page" key={order}><h2>{r.items.find(i=>(i.topico_ordem??0)===order)?.topico_nome||'Observações'}</h2>{r.items.filter(i=>(i.topico_ordem??0)===order).map(i=>{const a=answerMap.get(i.id);const isNo=a&&!a.nao_aplicavel&&a.resposta?.valor==='nao';const narrative=a&&(r.model==='headchef_narrativo'||i.tipo_resposta==='texto_livre'||i.tipo_resposta==='texto');const photos=r.photos.filter(p=>p.response_id===a?.id);const first=a?.foto_url;if(first&&!photos.some(p=>p.url===first))photos.unshift({id:`legacy-${i.id}`,response_id:a!.id,url:first,legenda:'',ordem:-1});return <article key={i.id} className={isNo||narrative?'cr-print-finding':'cr-print-compact'}><h3>{i.titulo}</h3><p>{a?.nao_aplicavel?'Não aplicável':isNo?'Não conforme':a?.resposta?.valor==='sim'?'Conforme':narrative?String(a?.resposta?.texto||'Registro descritivo'):'Não respondido'}</p>{(isNo||narrative)&&<><p>{a?.comentario||'Sem observação adicional.'}</p><p><b>Orientação corretiva:</b> {a?.orientacao_corretiva||r.actions.find(x=>x.response_id===a?.id)?.orientacao||'A completar na revisão'}</p>{a?.responsavel_orientado&&<p><b>Pessoa orientada:</b> {a.responsavel_orientado}</p>}<div className="cr-print-photos">{photos.map(p=><figure key={p.id}>{imageUrl(p.url)?<img src={imageUrl(p.url)} alt={p.legenda||i.titulo||'Evidência da inspeção'}/>:<p>Foto indisponível: revise o anexo.</p>}<figcaption>{p.legenda||'Sem legenda'}</figcaption></figure>)}</div></>}</article>})}</section>)}
 <section className="print-page"><h2>Observações gerais</h2><p className="whitespace-pre-wrap">{e.observacoes_gerais||'Sem observações gerais registradas.'}</p><h2>Plano de ação</h2><table><thead><tr><th>Correção / orientação</th><th>Responsável</th><th>Prazo</th><th>Status</th></tr></thead><tbody>{r.actions.map(a=><tr key={a.id}><td>{a.descricao}<br/>{a.orientacao}</td><td>{a.responsavel_nome||'A definir'}</td><td>{a.prazo?.split('-').reverse().join('/')||'A definir'}</td><td>{a.revisao_pendente?'Em revisão':a.status.replaceAll('_',' ')}</td></tr>)}</tbody></table>{!r.actions.length&&<p>{e.plano_revisado_em?'Sem ações corretivas.':'Plano ainda não liberado.'}</p>}
 <div className="cr-print-signatures print-avoid"><div>{imageUrl(e.assinatura_avaliador_url)&&<img src={imageUrl(e.assinatura_avaliador_url)} alt="Assinatura do avaliador"/>}<hr/><p>{e.avaliador_nome||'Nome do avaliador'}<br/>{e.avaliador_cargo||'Avaliador'} · {e.avaliador_registro||'Registro não informado'}</p></div><div><div className="cr-print-sign-space"/><hr/><p>Responsável da unidade<br/>Nome: __________________________________<br/>CPF: ___________________________________</p></div></div></section>
 <footer>CRIVO · {r.unit} · Identificação da visita {id}</footer></main>;
}
