import {buildCrivoPdf} from '../src/lib/crivo/pdf.ts'
import {PDFDocument} from 'pdf-lib'
import {writeFileSync} from 'node:fs'
import assert from 'node:assert/strict'
const report={execution:{id:'00000000-0000-4000-8000-000000000000',status:'concluido',percentual:66.67,concluido_em:'2026-10-05',avaliador_nome:'Auditor de demonstração',avaliador_registro:'REGISTRO DEMONSTRATIVO',assinatura_avaliador_url:null,responsavel_unidade_nome:'Responsável de demonstração',observacoes_gerais:'EXEMPLO FICTÍCIO. A visita identificou oportunidades de correção na rotina de armazenamento. Nenhuma informação deste documento representa uma auditoria real.',report_version:1},title:'Inspeção de higiene · exemplo fictício',unit:'Unidade de demonstração',local:'Cozinha',address:'Endereço demonstrativo',model:'headchef_conformidade',legacy:false,topics:[{topico_ordem:1,topico_nome:'Armazenamento',percentual:66.67,peso:3,zerado_por_critico:false,conformes:2,avaliados:3}],items:[{id:'i1',titulo:'Identificação dos alimentos',topico_nome:'Armazenamento',topico_ordem:1,tipo_resposta:'sim_nao',peso:1}],responses:[{id:'r1',item_id:'i1',resposta:{valor:'nao'},nao_aplicavel:false,comentario:'Exemplo de achado com acentuação: ausência de identificação.',foto_url:'demo',orientacao_corretiva:'Revisar identificação antes da abertura.'}],photos:[{response_id:'r1',url:'demo',legenda:'Figura demonstrativa — sem foto real de operação.'}],actions:[{id:'a1',response_id:'r1',descricao:'Identificar recipientes',orientacao:'Aplicar identificação legível com data e responsável.',responsavel_nome:'Líder de demonstração',prazo:'2026-10-07',status:'aberto',evidencia_url:null}],employees:[],canEdit:true}
const bytes=await buildCrivoPdf(report,[{key:'demo',type:'png',bytes:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aMioAAAAASUVORK5CYII=','base64')}]);const pdf=await PDFDocument.load(bytes);assert.ok(pdf.getPageCount()>=5);assert.equal(pdf.getTitle(),`${report.title} — ${report.unit}`);writeFileSync('/tmp/mise-crivo-laudo-exemplo.pdf',bytes)
const narrative=await buildCrivoPdf({...report,model:'headchef_narrativo',execution:{...report.execution,percentual:null},topics:report.topics.map(t=>({...t,percentual:null}))},[]);assert.ok((await PDFDocument.load(narrative)).getPageCount()>=5)
console.log('PASS PDF quantitative + narrative, pagination, accents, photo, captions, action plan and unsigned signature field')

const noPhoto=await buildCrivoPdf({...report,items:report.items.map(i=>({...i,requer_foto:'sim'})),responses:report.responses.map(r=>({...r,foto_url:null})),photos:[]},[]);writeFileSync('/tmp/mise-crivo-laudo-sem-foto.pdf',noPhoto);assert.ok((await PDFDocument.load(noPhoto)).getPageCount()>=5);
